### ISSUE TITLE
isImagePasteEnabled does not behave as expected

### ISSUE THREAD

**Issue by eliburke** [nathantannar4/InputBarAccessoryView#101]
When pasting an image and _InputTextView.isImagePasteEnabled_ = true:
_canPerformAction()_ allows the image to be pasted, and _paste()_ calls _pasteImageInTextContainer()_

When pasting an image and _InputTextView.isImagePasteEnabled_ = false
_canPerformAction()_ returns false

This behavior aligns with the name of the property _isImagePasteEnabled_, BUT the implementation of _InputTextView.paste_ contains [unreachable code](https://github.com/nathantannar4/InputBarAccessoryView/blob/5532f4e38155e6bb62075d13d153f87ac68e0970/Sources/Views/InputTextView.swift#L248) that loops through the Input Plugins and invokes handleInput for each one. It seems the intent was to either pass images into the TextView as attachments, OR pass them to the attachment manager to be inserted as attachments. 

At the moment I'm relying on overriding the inputTextView with a custom subclass that overrides paste, but I'd be happy to submit a PR to fix this, if I know how you would like to have it fixed. If you release a new version I could deprecate isImagePasteEnabled. Or, I could add a second variable such as pasteImagesAsAttachments = true, preserving current behavior.

**Comment by nathantannar4** [comment]
Yes, taking a look I see there is some unreachable code. I think from before where I had it so that image paste was sent to plugins, ie the attachment manager, but then I made it so that images can be pasted into the InputTextView itself. I think `canPerformAction` should return `true` if `isImagePasteEnabled` or if `inputBarAccessoryView?.inputPlugins.count > 0`

Happy to take PRs since you found this. @austinwright can help get it merged in 😊

**Comment by eliburke** [comment]
Submitted PR #114 
@austinwright lmk if you want it tweaked. Or feel free to change yourself whatever is easiest.

**Comment by austinwright** [comment]
Thanks Eli, I will not have time to look at this today but will try tonight or tomorrow.

**Comment by nathantannar4** [comment]
This issue has become stale/outdated. Please re-open if desired.
