### ISSUE TITLE
Focussing input text view before view appeared

### ISSUE THREAD

**Issue by brod-ie** [nathantannar4/InputBarAccessoryView#17]
We've found `self.bar.inputTextView.becomeFirstResponder()` has to be called in or after `viewDidAppear`. Placing this call earlier in the view's lifecycle has no effect. We've also tried calling `becomeFirstResponder()` then this call to no avail.

We'd like the input text view to be focussed without animation immediately (akin to Messenger). How can we go about this?

**Comment by nathantannar4** [comment]
Remember for an InputAccessoryView to be visible it's the ViewController itself that should be the first responder. Make sure `canBecomeFirstResponder` is overridden to true. Then by default the bar will be there when the ViewController is displayed. Also I don't think iOS will allow something to be the first responder when it's not visible which is why it has no effect. Is that what you mean by become available?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by brod-ie** [comment]
Yes we've tried putting `becomeFirstResponder()` early on too with no luck. Indeed `canBecomeFirstResponder` is overridden.

[From this SO answer](https://stackoverflow.com/questions/15472784/becomefirstresponder-works-in-viewdidappear-but-doesnt-work-in-viewdidload) I've learnt to achieve this `DispatchQueue.main.async` needs to be used.
