### ISSUE TITLE
Swift 4.2 Issue

### ISSUE THREAD

**Issue by murdeee** [nathantannar4/InputBarAccessoryView#33]
Not all warnings and renames was changed in last update.
For example
![2018-09-21 15 41 22](https://user-images.githubusercontent.com/20534235/45881776-dd568d00-bdb4-11e8-9153-6a3faa9ce765.png)

**Comment by nathantannar4** [comment]
v4.0.0 Works on Swift 4.2 for me, iare you sure you updated?

**Comment by BabyAzerty** [comment]
I had this problem too and also on other swift projects. It's probably a bug with either xcode 10 or MacOS Mojave or Cocoapods (not sure which), but for me the solution was going to 

Pods > Builds Settings > And specifying Swift 4.2 instead of Swift 4.0

![screenshot solution](https://user-images.githubusercontent.com/1152371/46068761-338f4b80-c17a-11e8-9b8c-01447654dd9e.png)
