### ISSUE TITLE
Animated height

### ISSUE THREAD

**Issue by lsmilek1** [nathantannar4/InputBarAccessoryView#69]
Hi, do I miss something essential, or there is not a way how to have the height being animated (like in whatsApp) and not just jump? Thank you!

**Comment by nathantannar4** [comment]
By default this isn't supported. When I tried making it animated it had some appearance issues on X devices caused by this being an inputAccessoryView. I can try to make some changes to resolve this 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by eliburke** [comment]
I'd like to have the AutocompleteManager animate into place, which is currently not possible because it calls reloadData() inside the private function layoutIfNeeded. I think one quick'n'dirty solution would be to change out `tableView.reloadData()` for
`tableView.reloadSections(NSIndexSet(index: 0), withRowAnimation: .Fade)`

I was able to kinda hack it in by subclassing AutocompleteManager:
```
class CustomAutocompleteManager: AutocompleteManager {
    @discardableResult override func handleInput(of object: AnyObject) -> Bool {
        UIView.animate(withDuration: 0.35) {
            super.handleInput(of: object)
        }
        return true
    }
}
```

Two problems: `textViewDidChange()` is not open so I can't animate the removal. And it's a bit janky. Better than nothing, but it would be nicer if the stack view's height animated up/down. 

If you could merge this PR I can maybe try and create a new one with similar implementation.

**Comment by Kaspik** [comment]
Try master or wait for next release please. :)
